<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['title' => 'Afghanistan', 'flag' => 'https://flagcdn.com/w320/af.png', 'phone_code' => '+93'],
            ['title' => 'Albania', 'flag' => 'https://flagcdn.com/w320/al.png', 'phone_code' => '+355'],
            ['title' => 'Algeria', 'flag' => 'https://flagcdn.com/w320/dz.png', 'phone_code' => '+213'],
            ['title' => 'Andorra', 'flag' => 'https://flagcdn.com/w320/ad.png', 'phone_code' => '+376'],
            ['title' => 'Angola', 'flag' => 'https://flagcdn.com/w320/ao.png', 'phone_code' => '+244'],
            ['title' => 'Antigua and Barbuda', 'flag' => 'https://flagcdn.com/w320/ag.png', 'phone_code' => '+1-268'],
            ['title' => 'Argentina', 'flag' => 'https://flagcdn.com/w320/ar.png', 'phone_code' => '+54'],
            ['title' => 'Armenia', 'flag' => 'https://flagcdn.com/w320/am.png', 'phone_code' => '+374'],
            ['title' => 'Australia', 'flag' => 'https://flagcdn.com/w320/au.png', 'phone_code' => '+61'],
            ['title' => 'Austria', 'flag' => 'https://flagcdn.com/w320/at.png', 'phone_code' => '+43'],
            ['title' => 'Azerbaijan', 'flag' => 'https://flagcdn.com/w320/az.png', 'phone_code' => '+994'],
            ['title' => 'Bahamas', 'flag' => 'https://flagcdn.com/w320/bs.png', 'phone_code' => '+1-242'],
            ['title' => 'Bahrain', 'flag' => 'https://flagcdn.com/w320/bh.png', 'phone_code' => '+973'],
            ['title' => 'Bangladesh', 'flag' => 'https://flagcdn.com/w320/bd.png', 'phone_code' => '+880'],
            ['title' => 'Barbados', 'flag' => 'https://flagcdn.com/w320/bb.png', 'phone_code' => '+1-246'],
            ['title' => 'Belarus', 'flag' => 'https://flagcdn.com/w320/by.png', 'phone_code' => '+375'],
            ['title' => 'Belgium', 'flag' => 'https://flagcdn.com/w320/be.png', 'phone_code' => '+32'],
            ['title' => 'Belize', 'flag' => 'https://flagcdn.com/w320/bz.png', 'phone_code' => '+501'],
            ['title' => 'Benin', 'flag' => 'https://flagcdn.com/w320/bj.png', 'phone_code' => '+229'],
            ['title' => 'Bhutan', 'flag' => 'https://flagcdn.com/w320/bt.png', 'phone_code' => '+975'],
            ['title' => 'Bolivia', 'flag' => 'https://flagcdn.com/w320/bo.png', 'phone_code' => '+591'],
            ['title' => 'Bosnia and Herzegovina', 'flag' => 'https://flagcdn.com/w320/ba.png', 'phone_code' => '+387'],
            ['title' => 'Botswana', 'flag' => 'https://flagcdn.com/w320/bw.png', 'phone_code' => '+267'],
            ['title' => 'Brazil', 'flag' => 'https://flagcdn.com/w320/br.png', 'phone_code' => '+55'],
            ['title' => 'Brunei', 'flag' => 'https://flagcdn.com/w320/bn.png', 'phone_code' => '+673'],
            ['title' => 'Bulgaria', 'flag' => 'https://flagcdn.com/w320/bg.png', 'phone_code' => '+359'],
            ['title' => 'Burkina Faso', 'flag' => 'https://flagcdn.com/w320/bf.png', 'phone_code' => '+226'],
            ['title' => 'Burundi', 'flag' => 'https://flagcdn.com/w320/bi.png', 'phone_code' => '+257'],
            ['title' => 'Côte d\'Ivoire', 'flag' => 'https://flagcdn.com/w320/ci.png', 'phone_code' => '+225'],
            ['title' => 'Cabo Verde', 'flag' => 'https://flagcdn.com/w320/cv.png', 'phone_code' => '+238'],
            ['title' => 'Cambodia', 'flag' => 'https://flagcdn.com/w320/kh.png', 'phone_code' => '+855'],
            ['title' => 'Cameroon', 'flag' => 'https://flagcdn.com/w320/cm.png', 'phone_code' => '+237'],
            ['title' => 'Canada', 'flag' => 'https://flagcdn.com/w320/ca.png', 'phone_code' => '+1'],
            ['title' => 'Central African Republic', 'flag' => 'https://flagcdn.com/w320/cf.png', 'phone_code' => '+236'],
            ['title' => 'Chad', 'flag' => 'https://flagcdn.com/w320/td.png', 'phone_code' => '+235'],
            ['title' => 'Chile', 'flag' => 'https://flagcdn.com/w320/cl.png', 'phone_code' => '+56'],
            ['title' => 'China', 'flag' => 'https://flagcdn.com/w320/cn.png', 'phone_code' => '+86'],
            ['title' => 'Colombia', 'flag' => 'https://flagcdn.com/w320/co.png', 'phone_code' => '+57'],
            ['title' => 'Comoros', 'flag' => 'https://flagcdn.com/w320/km.png', 'phone_code' => '+269'],
            ['title' => 'Congo (Congo-Brazzaville)', 'flag' => 'https://flagcdn.com/w320/cg.png', 'phone_code' => '+242'],
            ['title' => 'Congo (Congo-Kinshasa)', 'flag' => 'https://flagcdn.com/w320/cd.png', 'phone_code' => '+243'],
            ['title' => 'Costa Rica', 'flag' => 'https://flagcdn.com/w320/cr.png', 'phone_code' => '+506'],
            ['title' => 'Croatia', 'flag' => 'https://flagcdn.com/w320/hr.png', 'phone_code' => '+385'],
            ['title' => 'Cuba', 'flag' => 'https://flagcdn.com/w320/cu.png', 'phone_code' => '+53'],
            ['title' => 'Cyprus', 'flag' => 'https://flagcdn.com/w320/cy.png', 'phone_code' => '+357'],
            ['title' => 'Czech Republic', 'flag' => 'https://flagcdn.com/w320/cz.png', 'phone_code' => '+420'],
            ['title' => 'Denmark', 'flag' => 'https://flagcdn.com/w320/dk.png', 'phone_code' => '+45'],
            ['title' => 'Djibouti', 'flag' => 'https://flagcdn.com/w320/dj.png', 'phone_code' => '+253'],
            ['title' => 'Dominica', 'flag' => 'https://flagcdn.com/w320/dm.png', 'phone_code' => '+1-767'],
            ['title' => 'Dominican Republic', 'flag' => 'https://flagcdn.com/w320/do.png', 'phone_code' => '+1-809'],
            ['title' => 'Ecuador', 'flag' => 'https://flagcdn.com/w320/ec.png', 'phone_code' => '+593'],
            ['title' => 'Egypt', 'flag' => 'https://flagcdn.com/w320/eg.png', 'phone_code' => '+20'],
            ['title' => 'El Salvador', 'flag' => 'https://flagcdn.com/w320/sv.png', 'phone_code' => '+503'],
            ['title' => 'Equatorial Guinea', 'flag' => 'https://flagcdn.com/w320/gq.png', 'phone_code' => '+240'],
            ['title' => 'Eritrea', 'flag' => 'https://flagcdn.com/w320/er.png', 'phone_code' => '+291'],
            ['title' => 'Estonia', 'flag' => 'https://flagcdn.com/w320/ee.png', 'phone_code' => '+372'],
            ['title' => 'Eswatini', 'flag' => 'https://flagcdn.com/w320/sz.png', 'phone_code' => '+268'],
            ['title' => 'Ethiopia', 'flag' => 'https://flagcdn.com/w320/et.png', 'phone_code' => '+251'],
            ['title' => 'Fiji', 'flag' => 'https://flagcdn.com/w320/fj.png', 'phone_code' => '+679'],
            ['title' => 'Finland', 'flag' => 'https://flagcdn.com/w320/fi.png', 'phone_code' => '+358'],
            ['title' => 'France', 'flag' => 'https://flagcdn.com/w320/fr.png', 'phone_code' => '+33'],
            ['title' => 'Gabon', 'flag' => 'https://flagcdn.com/w320/ga.png', 'phone_code' => '+241'],
            ['title' => 'Gambia', 'flag' => 'https://flagcdn.com/w320/gm.png', 'phone_code' => '+220'],
            ['title' => 'Georgia', 'flag' => 'https://flagcdn.com/w320/ge.png', 'phone_code' => '+995'],
            ['title' => 'Germany', 'flag' => 'https://flagcdn.com/w320/de.png', 'phone_code' => '+49'],
            ['title' => 'Ghana', 'flag' => 'https://flagcdn.com/w320/gh.png', 'phone_code' => '+233'],
            ['title' => 'Greece', 'flag' => 'https://flagcdn.com/w320/gr.png', 'phone_code' => '+30'],
            ['title' => 'Grenada', 'flag' => 'https://flagcdn.com/w320/gd.png', 'phone_code' => '+1-473'],
            ['title' => 'Guatemala', 'flag' => 'https://flagcdn.com/w320/gt.png', 'phone_code' => '+502'],
            ['title' => 'Guinea', 'flag' => 'https://flagcdn.com/w320/gn.png', 'phone_code' => '+224'],
            ['title' => 'Guinea-Bissau', 'flag' => 'https://flagcdn.com/w320/gw.png', 'phone_code' => '+245'],
            ['title' => 'Guyana', 'flag' => 'https://flagcdn.com/w320/gy.png', 'phone_code' => '+592'],
            ['title' => 'Haiti', 'flag' => 'https://flagcdn.com/w320/ht.png', 'phone_code' => '+509'],
            ['title' => 'Honduras', 'flag' => 'https://flagcdn.com/w320/hn.png', 'phone_code' => '+504'],
            ['title' => 'Hungary', 'flag' => 'https://flagcdn.com/w320/hu.png', 'phone_code' => '+36'],
            ['title' => 'Iceland', 'flag' => 'https://flagcdn.com/w320/is.png', 'phone_code' => '+354'],
            ['title' => 'India', 'flag' => 'https://flagcdn.com/w320/in.png', 'phone_code' => '+91'],
            ['title' => 'Indonesia', 'flag' => 'https://flagcdn.com/w320/id.png', 'phone_code' => '+62'],
            ['title' => 'Iran', 'flag' => 'https://flagcdn.com/w320/ir.png', 'phone_code' => '+98'],
            ['title' => 'Iraq', 'flag' => 'https://flagcdn.com/w320/iq.png', 'phone_code' => '+964'],
            ['title' => 'Ireland', 'flag' => 'https://flagcdn.com/w320/ie.png', 'phone_code' => '+353'],
            ['title' => 'Israel', 'flag' => 'https://flagcdn.com/w320/il.png', 'phone_code' => '+972'],
            ['title' => 'Italy', 'flag' => 'https://flagcdn.com/w320/it.png', 'phone_code' => '+39'],
            ['title' => 'Jamaica', 'flag' => 'https://flagcdn.com/w320/jm.png', 'phone_code' => '+1-876'],
            ['title' => 'Japan', 'flag' => 'https://flagcdn.com/w320/jp.png', 'phone_code' => '+81'],
            ['title' => 'Jordan', 'flag' => 'https://flagcdn.com/w320/jo.png', 'phone_code' => '+962'],
            ['title' => 'Kazakhstan', 'flag' => 'https://flagcdn.com/w320/kz.png', 'phone_code' => '+7'],
            ['title' => 'Kenya', 'flag' => 'https://flagcdn.com/w320/ke.png', 'phone_code' => '+254'],
            ['title' => 'Kiribati', 'flag' => 'https://flagcdn.com/w320/ki.png', 'phone_code' => '+686'],
            ['title' => 'Kuwait', 'flag' => 'https://flagcdn.com/w320/kw.png', 'phone_code' => '+965'],
            ['title' => 'Kyrgyzstan', 'flag' => 'https://flagcdn.com/w320/kg.png', 'phone_code' => '+996'],
            ['title' => 'Laos', 'flag' => 'https://flagcdn.com/w320/la.png', 'phone_code' => '+856'],
            ['title' => 'Latvia', 'flag' => 'https://flagcdn.com/w320/lv.png', 'phone_code' => '+371'],
            ['title' => 'Lebanon', 'flag' => 'https://flagcdn.com/w320/lb.png', 'phone_code' => '+961'],
            ['title' => 'Lesotho', 'flag' => 'https://flagcdn.com/w320/ls.png', 'phone_code' => '+266'],
            ['title' => 'Liberia', 'flag' => 'https://flagcdn.com/w320/lr.png', 'phone_code' => '+231'],
            ['title' => 'Libya', 'flag' => 'https://flagcdn.com/w320/ly.png', 'phone_code' => '+218'],
            ['title' => 'Liechtenstein', 'flag' => 'https://flagcdn.com/w320/li.png', 'phone_code' => '+423'],
            ['title' => 'Lithuania', 'flag' => 'https://flagcdn.com/w320/lt.png', 'phone_code' => '+370'],
            ['title' => 'Luxembourg', 'flag' => 'https://flagcdn.com/w320/lu.png', 'phone_code' => '+352'],
            ['title' => 'Madagascar', 'flag' => 'https://flagcdn.com/w320/mg.png', 'phone_code' => '+261'],
            ['title' => 'Malawi', 'flag' => 'https://flagcdn.com/w320/mw.png', 'phone_code' => '+265'],
            ['title' => 'Malaysia', 'flag' => 'https://flagcdn.com/w320/my.png', 'phone_code' => '+60'],
            ['title' => 'Maldives', 'flag' => 'https://flagcdn.com/w320/mv.png', 'phone_code' => '+960'],
            ['title' => 'Mali', 'flag' => 'https://flagcdn.com/w320/ml.png', 'phone_code' => '+223'],
            ['title' => 'Malta', 'flag' => 'https://flagcdn.com/w320/mt.png', 'phone_code' => '+356'],
            ['title' => 'Marshall Islands', 'flag' => 'https://flagcdn.com/w320/mh.png', 'phone_code' => '+692'],
            ['title' => 'Mauritania', 'flag' => 'https://flagcdn.com/w320/mr.png', 'phone_code' => '+222'],
            ['title' => 'Mauritius', 'flag' => 'https://flagcdn.com/w320/mu.png', 'phone_code' => '+230'],
            ['title' => 'Mexico', 'flag' => 'https://flagcdn.com/w320/mx.png', 'phone_code' => '+52'],
            ['title' => 'Micronesia', 'flag' => 'https://flagcdn.com/w320/fm.png', 'phone_code' => '+691'],
            ['title' => 'Moldova', 'flag' => 'https://flagcdn.com/w320/md.png', 'phone_code' => '+373'],
            ['title' => 'Monaco', 'flag' => 'https://flagcdn.com/w320/mc.png', 'phone_code' => '+377'],
            ['title' => 'Mongolia', 'flag' => 'https://flagcdn.com/w320/mn.png', 'phone_code' => '+976'],
            ['title' => 'Montenegro', 'flag' => 'https://flagcdn.com/w320/me.png', 'phone_code' => '+382'],
            ['title' => 'Morocco', 'flag' => 'https://flagcdn.com/w320/ma.png', 'phone_code' => '+212'],
            ['title' => 'Mozambique', 'flag' => 'https://flagcdn.com/w320/mz.png', 'phone_code' => '+258'],
            ['title' => 'Myanmar', 'flag' => 'https://flagcdn.com/w320/mm.png', 'phone_code' => '+95'],
            ['title' => 'Namibia', 'flag' => 'https://flagcdn.com/w320/na.png', 'phone_code' => '+264'],
            ['title' => 'Nauru', 'flag' => 'https://flagcdn.com/w320/nr.png', 'phone_code' => '+674'],
            ['title' => 'Nepal', 'flag' => 'https://flagcdn.com/w320/np.png', 'phone_code' => '+977'],
            ['title' => 'Netherlands', 'flag' => 'https://flagcdn.com/w320/nl.png', 'phone_code' => '+31'],
            ['title' => 'New Zealand', 'flag' => 'https://flagcdn.com/w320/nz.png', 'phone_code' => '+64'],
            ['title' => 'Nicaragua', 'flag' => 'https://flagcdn.com/w320/ni.png', 'phone_code' => '+505'],
            ['title' => 'Niger', 'flag' => 'https://flagcdn.com/w320/ne.png', 'phone_code' => '+227'],
            ['title' => 'Nigeria', 'flag' => 'https://flagcdn.com/w320/ng.png', 'phone_code' => '+234'],
            ['title' => 'North Korea', 'flag' => 'https://flagcdn.com/w320/kp.png', 'phone_code' => '+850'],
            ['title' => 'North Macedonia', 'flag' => 'https://flagcdn.com/w320/mk.png', 'phone_code' => '+389'],
            ['title' => 'Norway', 'flag' => 'https://flagcdn.com/w320/no.png', 'phone_code' => '+47'],
            ['title' => 'Oman', 'flag' => 'https://flagcdn.com/w320/om.png', 'phone_code' => '+968'],
            ['title' => 'Pakistan', 'flag' => 'https://flagcdn.com/w320/pk.png', 'phone_code' => '+92'],
            ['title' => 'Palau', 'flag' => 'https://flagcdn.com/w320/pw.png', 'phone_code' => '+680'],
            ['title' => 'Palestine', 'flag' => 'https://flagcdn.com/w320/ps.png', 'phone_code' => '+970'],
            ['title' => 'Panama', 'flag' => 'https://flagcdn.com/w320/pa.png', 'phone_code' => '+507'],
            ['title' => 'Papua New Guinea', 'flag' => 'https://flagcdn.com/w320/pg.png', 'phone_code' => '+675'],
            ['title' => 'Paraguay', 'flag' => 'https://flagcdn.com/w320/py.png', 'phone_code' => '+595'],
            ['title' => 'Peru', 'flag' => 'https://flagcdn.com/w320/pe.png', 'phone_code' => '+51'],
            ['title' => 'Philippines', 'flag' => 'https://flagcdn.com/w320/ph.png', 'phone_code' => '+63'],
            ['title' => 'Poland', 'flag' => 'https://flagcdn.com/w320/pl.png', 'phone_code' => '+48'],
            ['title' => 'Portugal', 'flag' => 'https://flagcdn.com/w320/pt.png', 'phone_code' => '+351'],
            ['title' => 'Qatar', 'flag' => 'https://flagcdn.com/w320/qa.png', 'phone_code' => '+974'],
            ['title' => 'Romania', 'flag' => 'https://flagcdn.com/w320/ro.png', 'phone_code' => '+40'],
            ['title' => 'Russia', 'flag' => 'https://flagcdn.com/w320/ru.png', 'phone_code' => '+7'],
            ['title' => 'Rwanda', 'flag' => 'https://flagcdn.com/w320/rw.png', 'phone_code' => '+250'],
            ['title' => 'Saint Kitts and Nevis', 'flag' => 'https://flagcdn.com/w320/kn.png', 'phone_code' => '+1-869'],
            ['title' => 'Saint Lucia', 'flag' => 'https://flagcdn.com/w320/lc.png', 'phone_code' => '+1-758'],
            ['title' => 'Saint Vincent and the Grenadines', 'flag' => 'https://flagcdn.com/w320/vc.png', 'phone_code' => '+1-784'],
            ['title' => 'Samoa', 'flag' => 'https://flagcdn.com/w320/ws.png', 'phone_code' => '+685'],
            ['title' => 'San Marino', 'flag' => 'https://flagcdn.com/w320/sm.png', 'phone_code' => '+378'],
            ['title' => 'Sao Tome and Principe', 'flag' => 'https://flagcdn.com/w320/st.png', 'phone_code' => '+239'],
            ['title' => 'Saudi Arabia', 'flag' => 'https://flagcdn.com/w320/sa.png', 'phone_code' => '+966'],
            ['title' => 'Senegal', 'flag' => 'https://flagcdn.com/w320/sn.png', 'phone_code' => '+221'],
            ['title' => 'Serbia', 'flag' => 'https://flagcdn.com/w320/rs.png', 'phone_code' => '+381'],
            ['title' => 'Seychelles', 'flag' => 'https://flagcdn.com/w320/sc.png', 'phone_code' => '+248'],
            ['title' => 'Sierra Leone', 'flag' => 'https://flagcdn.com/w320/sl.png', 'phone_code' => '+232'],
            ['title' => 'Singapore', 'flag' => 'https://flagcdn.com/w320/sg.png', 'phone_code' => '+65'],
            ['title' => 'Slovakia', 'flag' => 'https://flagcdn.com/w320/sk.png', 'phone_code' => '+421'],
            ['title' => 'Slovenia', 'flag' => 'https://flagcdn.com/w320/si.png', 'phone_code' => '+386'],
            ['title' => 'Solomon Islands', 'flag' => 'https://flagcdn.com/w320/sb.png', 'phone_code' => '+677'],
            ['title' => 'Somalia', 'flag' => 'https://flagcdn.com/w320/so.png', 'phone_code' => '+252'],
            ['title' => 'South Africa', 'flag' => 'https://flagcdn.com/w320/za.png', 'phone_code' => '+27'],
            ['title' => 'South Korea', 'flag' => 'https://flagcdn.com/w320/kr.png', 'phone_code' => '+82'],
            ['title' => 'South Sudan', 'flag' => 'https://flagcdn.com/w320/ss.png', 'phone_code' => '+211'],
            ['title' => 'Spain', 'flag' => 'https://flagcdn.com/w320/es.png', 'phone_code' => '+34'],
            ['title' => 'Sri Lanka', 'flag' => 'https://flagcdn.com/w320/lk.png', 'phone_code' => '+94'],
            ['title' => 'Sudan', 'flag' => 'https://flagcdn.com/w320/sd.png', 'phone_code' => '+249'],
            ['title' => 'Suriname', 'flag' => 'https://flagcdn.com/w320/sr.png', 'phone_code' => '+597'],
            ['title' => 'Sweden', 'flag' => 'https://flagcdn.com/w320/se.png', 'phone_code' => '+46'],
            ['title' => 'Switzerland', 'flag' => 'https://flagcdn.com/w320/ch.png', 'phone_code' => '+41'],
            ['title' => 'Syria', 'flag' => 'https://flagcdn.com/w320/sy.png', 'phone_code' => '+963'],
            ['title' => 'Taiwan', 'flag' => 'https://flagcdn.com/w320/tw.png', 'phone_code' => '+886'],
            ['title' => 'Tajikistan', 'flag' => 'https://flagcdn.com/w320/tj.png', 'phone_code' => '+992'],
            ['title' => 'Tanzania', 'flag' => 'https://flagcdn.com/w320/tz.png', 'phone_code' => '+255'],
            ['title' => 'Thailand', 'flag' => 'https://flagcdn.com/w320/th.png', 'phone_code' => '+66'],
            ['title' => 'Timor-Leste', 'flag' => 'https://flagcdn.com/w320/tl.png', 'phone_code' => '+670'],
            ['title' => 'Togo', 'flag' => 'https://flagcdn.com/w320/tg.png', 'phone_code' => '+228'],
            ['title' => 'Tonga', 'flag' => 'https://flagcdn.com/w320/to.png', 'phone_code' => '+676'],
            ['title' => 'Trinidad and Tobago', 'flag' => 'https://flagcdn.com/w320/tt.png', 'phone_code' => '+1-868'],
            ['title' => 'Tunisia', 'flag' => 'https://flagcdn.com/w320/tn.png', 'phone_code' => '+216'],
            ['title' => 'Turkey', 'flag' => 'https://flagcdn.com/w320/tr.png', 'phone_code' => '+90'],
            ['title' => 'Turkmenistan', 'flag' => 'https://flagcdn.com/w320/tm.png', 'phone_code' => '+993'],
            ['title' => 'Tuvalu', 'flag' => 'https://flagcdn.com/w320/tv.png', 'phone_code' => '+688'],
            ['title' => 'Uganda', 'flag' => 'https://flagcdn.com/w320/ug.png', 'phone_code' => '+256'],
            ['title' => 'Ukraine', 'flag' => 'https://flagcdn.com/w320/ua.png', 'phone_code' => '+380'],
            ['title' => 'United Arab Emirates', 'flag' => 'https://flagcdn.com/w320/ae.png', 'phone_code' => '+971'],
            ['title' => 'United Kingdom', 'flag' => 'https://flagcdn.com/w320/gb.png', 'phone_code' => '+44'],
            ['title' => 'United States', 'flag' => 'https://flagcdn.com/w320/us.png', 'phone_code' => '+1'],
            ['title' => 'Uruguay', 'flag' => 'https://flagcdn.com/w320/uy.png', 'phone_code' => '+598'],
            ['title' => 'Uzbekistan', 'flag' => 'https://flagcdn.com/w320/uz.png', 'phone_code' => '+998'],
            ['title' => 'Vanuatu', 'flag' => 'https://flagcdn.com/w320/vu.png', 'phone_code' => '+678'],
            ['title' => 'Vatican City', 'flag' => 'https://flagcdn.com/w320/va.png', 'phone_code' => '+379'],
            ['title' => 'Venezuela', 'flag' => 'https://flagcdn.com/w320/ve.png', 'phone_code' => '+58'],
            ['title' => 'Vietnam', 'flag' => 'https://flagcdn.com/w320/vn.png', 'phone_code' => '+84'],
            ['title' => 'Yemen', 'flag' => 'https://flagcdn.com/w320/ye.png', 'phone_code' => '+967'],
            ['title' => 'Zambia', 'flag' => 'https://flagcdn.com/w320/zm.png', 'phone_code' => '+260'],
            ['title' => 'Zimbabwe', 'flag' => 'https://flagcdn.com/w320/zw.png', 'phone_code' => '+263'],
        ];

        DB::table('countries')->insert($countries);
    }
}
